import datetime

from modules.briefing_module import build_brief_details, build_due_reminder_alert
from modules.browser_automation_module import (
    browser_go_back,
    browser_go_forward,
    browser_refresh,
    browser_scroll_down,
    browser_scroll_up,
    copy_current_page_title,
    open_gmail,
    open_maps_search,
    open_whatsapp_web,
    open_youtube,
    search_google,
    search_youtube,
)
from modules.calendar_module import get_date, get_day, get_period, get_time
from modules.dashboard_module import build_dashboard_report, build_today_agenda
from modules.event_module import (
    add_event,
    clear_all_events,
    clear_past_events,
    clear_today_events,
    delete_event,
    delete_event_by_title,
    delete_latest_event,
    list_events,
    latest_event,
    rename_event,
    reschedule_event,
    today_events,
    upcoming_events,
)
from modules.export_module import export_productivity_summary
from modules.file_intelligence_module import (
    ask_found_file,
    find_file,
    open_found_file,
    recent_files,
    summarize_found_file,
)
from modules.health_module import (
    get_battery_status,
    get_cpu_status,
    get_disk_status,
    get_ram_status,
    get_system_status,
)
from modules.messaging_automation_module import (
    cancel_scheduled_whatsapp_message,
    cancel_scheduled_gmail_draft,
    draft_follow_up_email,
    draft_gmail,
    draft_job_application_email,
    draft_leave_email,
    draft_meeting_request_email,
    draft_professional_email,
    draft_thank_you_email,
    list_scheduled_gmail_drafts,
    list_scheduled_whatsapp_messages,
    open_gmail_and_type,
    open_whatsapp_and_type,
    schedule_gmail_draft,
    schedule_whatsapp_message,
    smart_gmail_draft,
    type_in_whatsapp,
    whatsapp_message_contact,
)
from modules.notification_module import (
    show_agenda_popup,
    show_event_popup,
    show_health_popup,
    show_notification_summary,
    show_reminder_popup,
    show_task_popup,
    show_weather_popup,
)
from modules.notes_module import (
    add_note,
    delete_note,
    latest_note,
    list_notes,
    search_notes,
    summarize_notes,
)
from modules.profile_module import (
    build_focus_suggestion,
    build_personal_snapshot,
    build_profile_summary,
    build_proactive_nudge,
)
from modules.weather_module import get_weather_report
from modules.window_context_module import (
    click_on_current_browser_page,
    describe_active_window,
    find_on_current_browser_page,
    get_active_app_name,
    get_active_window_title,
    get_current_browser_page_title,
    open_browser_result,
    summarize_active_window,
    summarize_browser_page,
    summarize_code_editor,
    summarize_if_browser,
    summarize_if_code_editor,
    summarize_if_file_explorer,
    summarize_visible_browser_section,
    summarize_current_folder,
    summarize_whatsapp_context,
)
from modules.routine_module import (
    create_custom_routine,
    delete_custom_routine,
    list_custom_routines,
    list_routines,
    run_routine,
)
from modules.task_module import (
    add_reminder,
    add_task,
    clear_all_reminders,
    clear_overdue_reminders,
    complete_task,
    complete_task_by_title,
    complete_all_tasks,
    complete_latest_task,
    delete_reminder,
    delete_reminder_by_title,
    delete_latest_reminder,
    delete_task,
    delete_task_by_title,
    delete_completed_tasks,
    delete_latest_task,
    due_today_summary,
    list_reminders,
    list_tasks,
    latest_reminder,
    latest_task,
    mark_all_tasks_done,
    mark_all_tasks_pending,
    overdue_items,
    rename_reminder,
    reschedule_reminder,
    snooze_reminder,
)


def _reply_text(handler_result):
    return {"handled": True, "reply": handler_result}


def _time_reply(_command):
    return f"The current time is {get_time()} and {get_period()}"


def _date_reply(_command):
    return f"Today's date is {get_date()}"


def _day_reply(_command):
    return f"Today is {get_day()}"


def _week_reply(_command):
    return f"This week is week number {datetime.datetime.now().isocalendar()[1]}"


def _month_reply(_command):
    return f"The current month is {datetime.datetime.now().strftime('%B')}"


def _year_reply(_command):
    return f"The current year is {datetime.datetime.now().year}"


COMMAND_REGISTRY = [
    {
        "intent": "time.current",
        "patterns": [
            "time now",
            "current time",
            "what time",
            "what is time",
            "what is the time",
            "what is the time now",
            "tell me the time",
        ],
        "type": "contains_any",
        "handler": _time_reply,
        "category": "date_time",
        "confidence": 0.95,
    },
    {
        "intent": "date.current",
        "patterns": [
            "today date",
            "current date",
            "what is date",
            "what is the date",
            "what is today's date",
        ],
        "type": "contains_any",
        "handler": _date_reply,
        "category": "date_time",
        "confidence": 0.95,
    },
    {
        "intent": "day.current",
        "patterns": ["what day", "today day"],
        "type": "contains_any",
        "handler": _day_reply,
        "category": "date_time",
        "confidence": 0.95,
    },
    {
        "intent": "week.current",
        "patterns": ["week number", "current week"],
        "type": "contains_any",
        "handler": _week_reply,
        "category": "date_time",
        "confidence": 0.9,
    },
    {
        "intent": "month.current",
        "patterns": ["what month", "current month"],
        "type": "contains_any",
        "handler": _month_reply,
        "category": "date_time",
        "confidence": 0.9,
    },
    {
        "intent": "year.current",
        "patterns": ["what year", "current year"],
        "type": "contains_any",
        "handler": _year_reply,
        "category": "date_time",
        "confidence": 0.9,
    },
    {
        "intent": "weather.current",
        "patterns": [
            "weather",
            "what is the weather",
            "today weather",
            "weather today",
            "weather in",
            "forecast in",
        ],
        "type": "weather",
        "handler": get_weather_report,
        "category": "weather",
        "confidence": 0.96,
    },
    {
        "intent": "brief.daily",
        "patterns": ["daily brief", "morning brief", "brief me", "status report"],
        "type": "exact",
        "handler": lambda command: build_brief_details(),
        "category": "briefing",
        "confidence": 0.98,
    },
    {
        "intent": "dashboard.report",
        "patterns": ["dashboard", "status center", "my day summary", "full report"],
        "type": "exact",
        "handler": lambda command: build_dashboard_report(),
        "category": "dashboard",
        "confidence": 0.98,
    },
    {
        "intent": "agenda.today",
        "patterns": ["today agenda", "my agenda", "plan my day", "today plan"],
        "type": "exact",
        "handler": lambda command: build_today_agenda(),
        "category": "dashboard",
        "confidence": 0.98,
    },
    {
        "intent": "export.summary",
        "patterns": [
            "export summary",
            "export productivity summary",
            "export task reminder event summary",
            "save summary report",
        ],
        "type": "exact",
        "handler": export_productivity_summary,
        "category": "export",
        "confidence": 0.97,
    },
    {
        "intent": "events.add",
        "patterns": ["add event", "create event", "schedule event"],
        "type": "startswith",
        "handler": add_event,
        "category": "events",
        "confidence": 0.98,
    },
    {
        "intent": "events.list",
        "patterns": ["list events", "show events", "my events"],
        "type": "exact",
        "handler": lambda command: list_events(),
        "category": "events",
        "confidence": 0.98,
    },
    {
        "intent": "events.today",
        "patterns": ["today events", "what are my events today", "today schedule"],
        "type": "exact",
        "handler": lambda command: today_events(),
        "category": "events",
        "confidence": 0.98,
    },
    {
        "intent": "events.upcoming",
        "patterns": ["upcoming events", "next events", "future events"],
        "type": "exact",
        "handler": lambda command: upcoming_events(),
        "category": "events",
        "confidence": 0.98,
    },
    {
        "intent": "events.latest",
        "patterns": ["latest event", "last event", "my latest event"],
        "type": "exact",
        "handler": lambda command: latest_event(),
        "category": "events",
        "confidence": 0.98,
    },
    {
        "intent": "events.delete_latest",
        "patterns": ["delete latest event", "remove latest event"],
        "type": "exact",
        "handler": lambda command: delete_latest_event(),
        "category": "events",
        "confidence": 0.98,
    },
    {
        "intent": "events.delete_by_title",
        "patterns": ["delete event about", "delete event titled", "remove event about", "remove event titled"],
        "type": "startswith",
        "handler": delete_event_by_title,
        "category": "events",
        "confidence": 0.98,
    },
    {
        "intent": "events.delete",
        "patterns": ["delete event"],
        "type": "startswith",
        "handler": delete_event,
        "category": "events",
        "confidence": 0.98,
    },
    {
        "intent": "events.rename",
        "patterns": ["rename event about", "rename event titled"],
        "type": "startswith",
        "handler": rename_event,
        "category": "events",
        "confidence": 0.98,
    },
    {
        "intent": "events.reschedule",
        "patterns": ["reschedule event about", "reschedule event titled"],
        "type": "startswith",
        "handler": reschedule_event,
        "category": "events",
        "confidence": 0.98,
    },
    {
        "intent": "events.clear_all",
        "patterns": ["clear all events", "delete all events", "remove all events"],
        "type": "exact",
        "handler": lambda command: clear_all_events(),
        "category": "events",
        "confidence": 0.98,
    },
    {
        "intent": "events.clear_today",
        "patterns": ["clear today events", "delete today events", "remove today events"],
        "type": "exact",
        "handler": lambda command: clear_today_events(),
        "category": "events",
        "confidence": 0.98,
    },
    {
        "intent": "events.clear_past",
        "patterns": ["clear past events", "delete past events", "remove past events"],
        "type": "exact",
        "handler": lambda command: clear_past_events(),
        "category": "events",
        "confidence": 0.98,
    },
    {
        "intent": "files.find",
        "patterns": ["find file", "search file", "locate file"],
        "type": "startswith",
        "handler": find_file,
        "category": "file_intelligence",
        "confidence": 0.97,
    },
    {
        "intent": "files.open",
        "patterns": ["open file named", "open found file"],
        "type": "startswith",
        "handler": open_found_file,
        "category": "file_intelligence",
        "confidence": 0.97,
    },
    {
        "intent": "files.recent",
        "patterns": ["recent files", "show recent files", "latest files"],
        "type": "exact",
        "handler": lambda command: recent_files(),
        "category": "file_intelligence",
        "confidence": 0.97,
    },
    {
        "intent": "files.summary",
        "patterns": ["summarize file", "read file summary", "what is in file"],
        "type": "startswith",
        "handler": summarize_found_file,
        "category": "file_intelligence",
        "confidence": 0.97,
    },
    {
        "intent": "files.qa",
        "patterns": [
            "ask file",
            "ask pdf",
            "ask document",
            "what does file",
            "search document",
        ],
        "type": "startswith",
        "handler": ask_found_file,
        "category": "file_intelligence",
        "confidence": 0.97,
    },
    {
        "intent": "health.system",
        "patterns": ["system status", "health status", "system health", "pc health"],
        "type": "exact",
        "handler": lambda command: get_system_status(),
        "category": "system_health",
        "confidence": 0.97,
    },
    {
        "intent": "health.cpu",
        "patterns": ["cpu usage", "cpu status"],
        "type": "exact",
        "handler": lambda command: get_cpu_status(),
        "category": "system_health",
        "confidence": 0.97,
    },
    {
        "intent": "health.ram",
        "patterns": ["ram usage", "memory usage", "ram status", "memory status"],
        "type": "exact",
        "handler": lambda command: get_ram_status(),
        "category": "system_health",
        "confidence": 0.97,
    },
    {
        "intent": "health.disk",
        "patterns": ["disk usage", "disk status", "storage status"],
        "type": "exact",
        "handler": lambda command: get_disk_status(),
        "category": "system_health",
        "confidence": 0.97,
    },
    {
        "intent": "health.battery",
        "patterns": ["battery status", "battery health"],
        "type": "exact",
        "handler": lambda command: get_battery_status(),
        "category": "system_health",
        "confidence": 0.97,
    },
    {
        "intent": "messaging.gmail.schedule",
        "patterns": ["schedule gmail draft to", "send gmail draft to"],
        "type": "startswith",
        "handler": schedule_gmail_draft,
        "category": "messaging_automation",
        "confidence": 0.97,
    },
    {
        "intent": "messaging.whatsapp.schedule",
        "patterns": ["schedule whatsapp message to", "send whatsapp message to"],
        "type": "startswith",
        "handler": schedule_whatsapp_message,
        "category": "messaging_automation",
        "confidence": 0.97,
    },
    {
        "intent": "messaging.whatsapp.open_and_type",
        "patterns": ["open whatsapp web and type"],
        "type": "startswith",
        "handler": open_whatsapp_and_type,
        "category": "messaging_automation",
        "confidence": 0.97,
    },
    {
        "intent": "messaging.whatsapp.schedule.list",
        "patterns": ["list scheduled whatsapp messages", "show scheduled whatsapp messages"],
        "type": "exact",
        "handler": lambda command: list_scheduled_whatsapp_messages(),
        "category": "messaging_automation",
        "confidence": 0.97,
    },
    {
        "intent": "messaging.gmail.schedule.list",
        "patterns": ["list scheduled gmail drafts", "show scheduled gmail drafts"],
        "type": "exact",
        "handler": lambda command: list_scheduled_gmail_drafts(),
        "category": "messaging_automation",
        "confidence": 0.97,
    },
    {
        "intent": "messaging.whatsapp.schedule.cancel",
        "patterns": ["cancel scheduled whatsapp message", "delete scheduled whatsapp message"],
        "type": "startswith",
        "handler": cancel_scheduled_whatsapp_message,
        "category": "messaging_automation",
        "confidence": 0.97,
    },
    {
        "intent": "messaging.gmail.schedule.cancel",
        "patterns": ["cancel scheduled gmail draft", "delete scheduled gmail draft"],
        "type": "startswith",
        "handler": cancel_scheduled_gmail_draft,
        "category": "messaging_automation",
        "confidence": 0.97,
    },
    {
        "intent": "messaging.whatsapp.type",
        "patterns": ["type in whatsapp"],
        "type": "startswith",
        "handler": type_in_whatsapp,
        "category": "messaging_automation",
        "confidence": 0.97,
    },
    {
        "intent": "messaging.gmail.open_and_type",
        "patterns": ["open gmail and type"],
        "type": "startswith",
        "handler": open_gmail_and_type,
        "category": "messaging_automation",
        "confidence": 0.97,
    },
    {
        "intent": "messaging.gmail.job_application_template",
        "patterns": [
            "draft job application mail to",
            "draft job application email to",
            "write job application mail to",
        ],
        "type": "startswith",
        "handler": draft_job_application_email,
        "category": "messaging_automation",
        "confidence": 0.98,
    },
    {
        "intent": "messaging.gmail.meeting_request_template",
        "patterns": [
            "draft meeting request mail to",
            "draft meeting request email to",
            "write meeting request mail to",
        ],
        "type": "startswith",
        "handler": draft_meeting_request_email,
        "category": "messaging_automation",
        "confidence": 0.98,
    },
    {
        "intent": "messaging.gmail.thank_you_template",
        "patterns": [
            "draft thank you mail to",
            "draft thank you email to",
            "write thank you mail to",
        ],
        "type": "startswith",
        "handler": draft_thank_you_email,
        "category": "messaging_automation",
        "confidence": 0.98,
    },
    {
        "intent": "messaging.gmail.professional_template",
        "patterns": [
            "draft professional email to",
            "compose professional email to",
            "write professional mail to",
        ],
        "type": "startswith",
        "handler": draft_professional_email,
        "category": "messaging_automation",
        "confidence": 0.98,
    },
    {
        "intent": "messaging.gmail.leave_template",
        "patterns": [
            "draft leave mail to",
            "draft leave email to",
            "write leave mail to",
        ],
        "type": "startswith",
        "handler": draft_leave_email,
        "category": "messaging_automation",
        "confidence": 0.98,
    },
    {
        "intent": "messaging.gmail.followup_template",
        "patterns": [
            "draft follow up mail to",
            "draft follow-up mail to",
            "write follow up email to",
        ],
        "type": "startswith",
        "handler": draft_follow_up_email,
        "category": "messaging_automation",
        "confidence": 0.98,
    },
    {
        "intent": "messaging.gmail.smart_draft",
        "patterns": ["draft gmail to", "gmail draft to", "compose gmail to"],
        "type": "startswith",
        "handler": smart_gmail_draft,
        "category": "messaging_automation",
        "confidence": 0.98,
    },
    {
        "intent": "messaging.gmail.draft",
        "patterns": ["draft gmail"],
        "type": "startswith",
        "handler": draft_gmail,
        "category": "messaging_automation",
        "confidence": 0.97,
    },
    {
        "intent": "messaging.whatsapp.contact_message",
        "patterns": ["message on whatsapp", "send whatsapp message to", "open whatsapp and message"],
        "type": "startswith",
        "handler": whatsapp_message_contact,
        "category": "messaging_automation",
        "confidence": 0.98,
    },
    {
        "intent": "notes.add",
        "patterns": ["take a note", "save this idea", "save note", "add note", "note this"],
        "type": "startswith",
        "handler": add_note,
        "category": "notes",
        "confidence": 0.98,
    },
    {
        "intent": "notes.list",
        "patterns": ["list notes", "show notes", "my notes"],
        "type": "exact",
        "handler": lambda command: list_notes(),
        "category": "notes",
        "confidence": 0.98,
    },
    {
        "intent": "notes.search",
        "patterns": ["search notes for", "find note about", "find note", "search notes"],
        "type": "startswith",
        "handler": search_notes,
        "category": "notes",
        "confidence": 0.97,
    },
    {
        "intent": "notes.latest",
        "patterns": ["latest note", "last note", "my latest note"],
        "type": "exact",
        "handler": lambda command: latest_note(),
        "category": "notes",
        "confidence": 0.97,
    },
    {
        "intent": "notes.summary",
        "patterns": ["summarize notes", "notes summary", "note summary", "recap my notes"],
        "type": "exact",
        "handler": lambda command: summarize_notes(),
        "category": "notes",
        "confidence": 0.97,
    },
    {
        "intent": "browser.search.google",
        "patterns": ["search google for", "search for", "search", "google"],
        "type": "startswith",
        "handler": search_google,
        "category": "browser_automation",
        "confidence": 0.94,
    },
    {
        "intent": "browser.search.youtube",
        "patterns": ["search youtube for", "open youtube and search", "youtube search"],
        "type": "startswith",
        "handler": search_youtube,
        "category": "browser_automation",
        "confidence": 0.95,
    },
    {
        "intent": "browser.open.youtube",
        "patterns": ["open youtube"],
        "type": "exact",
        "handler": lambda command: open_youtube(),
        "category": "browser_automation",
        "confidence": 0.98,
    },
    {
        "intent": "browser.open.whatsapp_web",
        "patterns": ["open whatsapp web", "start whatsapp web"],
        "type": "exact",
        "handler": lambda command: open_whatsapp_web(),
        "category": "browser_automation",
        "confidence": 0.98,
    },
    {
        "intent": "browser.open.gmail",
        "patterns": ["open gmail", "open google mail"],
        "type": "exact",
        "handler": lambda command: open_gmail(),
        "category": "browser_automation",
        "confidence": 0.98,
    },
    {
        "intent": "browser.open.maps",
        "patterns": ["open maps for", "find place", "search maps for"],
        "type": "startswith",
        "handler": open_maps_search,
        "category": "browser_automation",
        "confidence": 0.95,
    },
    {
        "intent": "browser.action.back",
        "patterns": ["go back", "browser back", "go to previous page"],
        "type": "exact",
        "handler": lambda command: browser_go_back(),
        "category": "browser_automation",
        "confidence": 0.95,
    },
    {
        "intent": "browser.action.forward",
        "patterns": ["go forward", "browser forward", "go to next page"],
        "type": "exact",
        "handler": lambda command: browser_go_forward(),
        "category": "browser_automation",
        "confidence": 0.95,
    },
    {
        "intent": "browser.action.refresh",
        "patterns": ["refresh page", "refresh browser", "reload page"],
        "type": "exact",
        "handler": lambda command: browser_refresh(),
        "category": "browser_automation",
        "confidence": 0.95,
    },
    {
        "intent": "browser.action.scroll_down",
        "patterns": ["scroll down", "page down", "scroll browser down"],
        "type": "exact",
        "handler": lambda command: browser_scroll_down(),
        "category": "browser_automation",
        "confidence": 0.94,
    },
    {
        "intent": "browser.action.scroll_up",
        "patterns": ["scroll up", "page up", "scroll browser up"],
        "type": "exact",
        "handler": lambda command: browser_scroll_up(),
        "category": "browser_automation",
        "confidence": 0.94,
    },
    {
        "intent": "browser.action.copy_title",
        "patterns": ["copy current page title", "copy page title", "copy browser title"],
        "type": "exact",
        "handler": copy_current_page_title,
        "category": "browser_automation",
        "confidence": 0.94,
    },
    {
        "intent": "browser.action.open_result",
        "patterns": [
            "open first search result",
            "open first result",
            "click top result",
            "open top result",
            "open second search result",
            "open second result",
            "open third search result",
            "open third result",
        ],
        "type": "exact",
        "handler": open_browser_result,
        "category": "browser_automation",
        "confidence": 0.93,
    },
    {
        "intent": "notes.delete",
        "patterns": ["delete note"],
        "type": "startswith",
        "handler": delete_note,
        "category": "notes",
        "confidence": 0.98,
    },
    {
        "intent": "profile.summary",
        "patterns": [
            "tell me about myself",
            "summarize my profile",
            "my profile summary",
            "who am i really",
        ],
        "type": "exact",
        "handler": lambda command: build_profile_summary(),
        "category": "profile",
        "confidence": 0.98,
    },
    {
        "intent": "profile.focus",
        "patterns": [
            "what should i focus on",
            "what should i do next",
            "what is my focus",
            "guide my focus",
        ],
        "type": "exact",
        "handler": lambda command: build_focus_suggestion(),
        "category": "profile",
        "confidence": 0.98,
    },
    {
        "intent": "profile.snapshot",
        "patterns": [
            "personal snapshot",
            "tell me my habits",
            "summarize my personal details",
        ],
        "type": "exact",
        "handler": lambda command: build_personal_snapshot(),
        "category": "profile",
        "confidence": 0.97,
    },
    {
        "intent": "profile.nudge",
        "patterns": [
            "give me a suggestion",
            "give me a nudge",
            "motivate me",
            "what should i do now",
            "any suggestion for me",
        ],
        "type": "exact",
        "handler": lambda command: build_proactive_nudge(),
        "category": "profile",
        "confidence": 0.97,
    },
    {
        "intent": "window.active_app",
        "patterns": [
            "what app am i using",
            "which app am i using",
            "what application is open",
        ],
        "type": "exact",
        "handler": lambda command: get_active_app_name(),
        "category": "window_context",
        "confidence": 0.97,
    },
    {
        "intent": "window.active_title",
        "patterns": [
            "what window is open",
            "what is the current window",
            "what is my current window",
        ],
        "type": "exact",
        "handler": lambda command: get_active_window_title(),
        "category": "window_context",
        "confidence": 0.97,
    },
    {
        "intent": "window.describe",
        "patterns": [
            "what am i seeing",
            "what am i looking at",
            "describe my screen",
            "describe active window",
        ],
        "type": "exact",
        "handler": lambda command: summarize_active_window(),
        "category": "window_context",
        "confidence": 0.97,
    },
    {
        "intent": "window.browser",
        "patterns": [
            "am i in browser",
            "what tab is open",
            "summarize this page",
            "which tab is open",
        ],
        "type": "exact",
        "handler": lambda command: summarize_if_browser(),
        "category": "window_context",
        "confidence": 0.96,
    },
    {
        "intent": "app.browser.summary",
        "patterns": [
            "summarize current browser page",
            "read current browser page",
            "summarize browser page",
        ],
        "type": "exact",
        "handler": lambda command: summarize_browser_page(),
        "category": "app_intelligence",
        "confidence": 0.96,
    },
    {
        "intent": "app.browser.title",
        "patterns": [
            "what is the current page title",
            "what page am i on",
            "current page title",
            "browser page title",
        ],
        "type": "exact",
        "handler": lambda command: get_current_browser_page_title(),
        "category": "app_intelligence",
        "confidence": 0.96,
    },
    {
        "intent": "app.browser.section",
        "patterns": [
            "summarize current visible section",
            "summarize visible section",
            "read current visible section",
            "read visible browser section",
        ],
        "type": "exact",
        "handler": lambda command: summarize_visible_browser_section(),
        "category": "app_intelligence",
        "confidence": 0.95,
    },
    {
        "intent": "app.browser.find",
        "patterns": [
            "search this page for",
            "find on this page",
            "find this page",
            "search page for",
        ],
        "type": "startswith",
        "handler": find_on_current_browser_page,
        "category": "app_intelligence",
        "confidence": 0.95,
    },
    {
        "intent": "app.browser.click",
        "patterns": [
            "click on this page",
            "click this page",
            "click first matching result for",
            "click first result for",
        ],
        "type": "startswith",
        "handler": click_on_current_browser_page,
        "category": "app_intelligence",
        "confidence": 0.95,
    },
    {
        "intent": "window.editor",
        "patterns": [
            "am i in vscode",
            "what file is open",
            "am i coding now",
            "which file is open",
        ],
        "type": "exact",
        "handler": lambda command: summarize_if_code_editor(),
        "category": "window_context",
        "confidence": 0.96,
    },
    {
        "intent": "app.editor.summary",
        "patterns": [
            "summarize current code editor",
            "summarize current file",
            "read current file context",
        ],
        "type": "exact",
        "handler": lambda command: summarize_code_editor(),
        "category": "app_intelligence",
        "confidence": 0.96,
    },
    {
        "intent": "window.explorer",
        "patterns": [
            "am i in file explorer",
            "which folder is open",
            "what folder is open",
        ],
        "type": "exact",
        "handler": lambda command: summarize_if_file_explorer(),
        "category": "window_context",
        "confidence": 0.96,
    },
    {
        "intent": "app.explorer.summary",
        "patterns": [
            "summarize current folder",
            "read current folder",
            "what folder am i in",
        ],
        "type": "exact",
        "handler": lambda command: summarize_current_folder(),
        "category": "app_intelligence",
        "confidence": 0.96,
    },
    {
        "intent": "app.whatsapp.summary",
        "patterns": [
            "summarize whatsapp",
            "what chat am i on",
            "read whatsapp screen",
        ],
        "type": "exact",
        "handler": lambda command: summarize_whatsapp_context(),
        "category": "app_intelligence",
        "confidence": 0.95,
    },
    {
        "intent": "window.describe_app",
        "patterns": [
            "describe current app",
            "tell me current app",
        ],
        "type": "exact",
        "handler": lambda command: describe_active_window(),
        "category": "window_context",
        "confidence": 0.96,
    },
    {
        "intent": "reminders.urgent",
        "patterns": ["check reminders", "due reminders", "urgent reminders"],
        "type": "exact",
        "handler": lambda command: build_due_reminder_alert(),
        "category": "briefing",
        "confidence": 0.98,
    },
    {
        "intent": "notifications.summary",
        "patterns": ["show notification", "show desktop notification", "notification summary", "desktop notification"],
        "type": "exact",
        "handler": lambda command: show_notification_summary(),
        "category": "notifications",
        "confidence": 0.96,
    },
    {
        "intent": "notifications.reminders",
        "patterns": ["show reminder popup", "reminder popup", "popup reminders"],
        "type": "exact",
        "handler": lambda command: show_reminder_popup(),
        "category": "notifications",
        "confidence": 0.96,
    },
    {
        "intent": "notifications.tasks",
        "patterns": ["show task popup", "task popup", "popup tasks"],
        "type": "exact",
        "handler": lambda command: show_task_popup(),
        "category": "notifications",
        "confidence": 0.96,
    },
    {
        "intent": "notifications.events",
        "patterns": ["show event popup", "event popup", "popup events", "calendar popup"],
        "type": "exact",
        "handler": lambda command: show_event_popup(),
        "category": "notifications",
        "confidence": 0.96,
    },
    {
        "intent": "notifications.health",
        "patterns": ["show health popup", "health popup", "system health popup"],
        "type": "exact",
        "handler": lambda command: show_health_popup(),
        "category": "notifications",
        "confidence": 0.96,
    },
    {
        "intent": "notifications.weather",
        "patterns": ["show weather popup", "weather popup", "popup weather", "desktop weather popup"],
        "type": "exact",
        "handler": lambda command: show_weather_popup(),
        "category": "notifications",
        "confidence": 0.96,
    },
    {
        "intent": "notifications.agenda",
        "patterns": ["show agenda popup", "agenda popup", "today agenda popup", "popup agenda"],
        "type": "exact",
        "handler": lambda command: show_agenda_popup(),
        "category": "notifications",
        "confidence": 0.96,
    },
    {
        "intent": "tasks.add",
        "patterns": ["add task"],
        "type": "startswith",
        "handler": add_task,
        "category": "tasks",
        "confidence": 0.98,
    },
    {
        "intent": "tasks.list",
        "patterns": ["show tasks", "list tasks", "my tasks"],
        "type": "exact",
        "handler": lambda command: list_tasks(),
        "category": "tasks",
        "confidence": 0.98,
    },
    {
        "intent": "tasks.complete",
        "patterns": ["complete task"],
        "type": "startswith",
        "handler": complete_task,
        "category": "tasks",
        "confidence": 0.98,
    },
    {
        "intent": "tasks.complete_by_title",
        "patterns": ["complete task titled", "complete task about"],
        "type": "startswith",
        "handler": complete_task_by_title,
        "category": "tasks",
        "confidence": 0.98,
    },
    {
        "intent": "tasks.complete_all",
        "patterns": ["complete all tasks", "finish all tasks", "mark all tasks done"],
        "type": "exact",
        "handler": lambda command: complete_all_tasks(),
        "category": "tasks",
        "confidence": 0.98,
    },
    {
        "intent": "tasks.complete_latest",
        "patterns": ["complete latest task", "finish latest task", "mark latest task done"],
        "type": "exact",
        "handler": lambda command: complete_latest_task(),
        "category": "tasks",
        "confidence": 0.98,
    },
    {
        "intent": "tasks.delete",
        "patterns": ["delete task"],
        "type": "startswith",
        "handler": delete_task,
        "category": "tasks",
        "confidence": 0.98,
    },
    {
        "intent": "tasks.delete_by_title",
        "patterns": ["delete task titled", "delete task about", "remove task titled", "remove task about"],
        "type": "startswith",
        "handler": delete_task_by_title,
        "category": "tasks",
        "confidence": 0.98,
    },
    {
        "intent": "tasks.delete_latest",
        "patterns": ["delete latest task", "remove latest task"],
        "type": "exact",
        "handler": lambda command: delete_latest_task(),
        "category": "tasks",
        "confidence": 0.98,
    },
    {
        "intent": "tasks.delete_completed",
        "patterns": ["delete completed tasks", "clear completed tasks", "remove completed tasks"],
        "type": "exact",
        "handler": lambda command: delete_completed_tasks(),
        "category": "tasks",
        "confidence": 0.98,
    },
    {
        "intent": "tasks.latest",
        "patterns": ["latest task", "last task", "my latest task"],
        "type": "exact",
        "handler": lambda command: latest_task(),
        "category": "tasks",
        "confidence": 0.97,
    },
    {
        "intent": "tasks.mark_pending",
        "patterns": ["mark all tasks pending", "set all tasks pending", "make all tasks pending"],
        "type": "exact",
        "handler": lambda command: mark_all_tasks_pending(),
        "category": "tasks",
        "confidence": 0.98,
    },
    {
        "intent": "tasks.mark_done",
        "patterns": ["mark all tasks done", "set all tasks done", "make all tasks done"],
        "type": "exact",
        "handler": lambda command: mark_all_tasks_done(),
        "category": "tasks",
        "confidence": 0.98,
    },
    {
        "intent": "reminders.add",
        "patterns": ["remind me to"],
        "type": "startswith",
        "handler": add_reminder,
        "category": "reminders",
        "confidence": 0.98,
    },
    {
        "intent": "reminders.list",
        "patterns": ["show reminders", "list reminders", "my reminders"],
        "type": "exact",
        "handler": lambda command: list_reminders(),
        "category": "reminders",
        "confidence": 0.98,
    },
    {
        "intent": "reminders.delete",
        "patterns": ["delete reminder"],
        "type": "startswith",
        "handler": delete_reminder,
        "category": "reminders",
        "confidence": 0.98,
    },
    {
        "intent": "reminders.delete_by_title",
        "patterns": [
            "delete reminder about",
            "delete reminder titled",
            "remove reminder about",
            "remove reminder titled",
        ],
        "type": "startswith",
        "handler": delete_reminder_by_title,
        "category": "reminders",
        "confidence": 0.98,
    },
    {
        "intent": "reminders.delete_latest",
        "patterns": ["delete latest reminder", "remove latest reminder"],
        "type": "exact",
        "handler": lambda command: delete_latest_reminder(),
        "category": "reminders",
        "confidence": 0.98,
    },
    {
        "intent": "reminders.clear_overdue",
        "patterns": ["clear overdue reminders", "delete overdue reminders", "remove overdue reminders"],
        "type": "exact",
        "handler": lambda command: clear_overdue_reminders(),
        "category": "reminders",
        "confidence": 0.98,
    },
    {
        "intent": "reminders.clear_all",
        "patterns": ["clear all reminders", "delete all reminders", "remove all reminders"],
        "type": "exact",
        "handler": lambda command: clear_all_reminders(),
        "category": "reminders",
        "confidence": 0.98,
    },
    {
        "intent": "reminders.latest",
        "patterns": ["latest reminder", "last reminder", "my latest reminder"],
        "type": "exact",
        "handler": lambda command: latest_reminder(),
        "category": "reminders",
        "confidence": 0.97,
    },
    {
        "intent": "reminders.due_today",
        "patterns": ["what is due today", "what's due today", "show due today", "due today"],
        "type": "exact",
        "handler": lambda command: due_today_summary(),
        "category": "reminders",
        "confidence": 0.97,
    },
    {
        "intent": "reminders.overdue",
        "patterns": ["show overdue items", "overdue items", "what is overdue", "what's overdue"],
        "type": "exact",
        "handler": lambda command: overdue_items(),
        "category": "reminders",
        "confidence": 0.97,
    },
    {
        "intent": "reminders.snooze",
        "patterns": ["snooze reminder", "snooze latest reminder"],
        "type": "startswith",
        "handler": snooze_reminder,
        "category": "reminders",
        "confidence": 0.97,
    },
    {
        "intent": "reminders.rename",
        "patterns": ["rename reminder about", "rename reminder titled"],
        "type": "startswith",
        "handler": rename_reminder,
        "category": "reminders",
        "confidence": 0.98,
    },
    {
        "intent": "reminders.reschedule",
        "patterns": ["reschedule reminder about", "reschedule reminder titled"],
        "type": "startswith",
        "handler": reschedule_reminder,
        "category": "reminders",
        "confidence": 0.98,
    },
    {
        "intent": "modes.list",
        "patterns": ["list modes", "show modes", "what modes do you have"],
        "type": "exact",
        "handler": lambda command: list_routines(),
        "category": "modes",
        "confidence": 0.98,
    },
    {
        "intent": "modes.custom.list",
        "patterns": ["list custom modes", "show custom modes", "my custom modes"],
        "type": "exact",
        "handler": lambda command: list_custom_routines(),
        "category": "modes",
        "confidence": 0.98,
    },
    {
        "intent": "modes.custom.create",
        "patterns": ["create mode"],
        "type": "startswith",
        "handler": create_custom_routine,
        "category": "modes",
        "confidence": 0.98,
    },
    {
        "intent": "modes.custom.delete",
        "patterns": ["delete mode"],
        "type": "startswith",
        "handler": delete_custom_routine,
        "category": "modes",
        "confidence": 0.98,
    },
    {
        "intent": "modes.start",
        "patterns": ["start"],
        "type": "mode_start",
        "handler": run_routine,
        "category": "modes",
        "confidence": 0.95,
    },
]


def _matches(command, entry):
    match_type = entry["type"]
    patterns = entry["patterns"]

    if match_type == "exact":
        return command in patterns

    if match_type == "startswith":
        return any(command.startswith(pattern) for pattern in patterns)

    if match_type == "contains_any":
        return any(pattern in command for pattern in patterns)

    if match_type == "mode_start":
        return command.startswith("start") and "mode" in command

    if match_type == "weather":
        return command in patterns[:4] or command.startswith("weather in") or command.startswith("forecast in")

    return False


def resolve_intent(command):
    command = command.lower().strip()

    for entry in COMMAND_REGISTRY:
        if _matches(command, entry):
            return {
                "intent": entry["intent"],
                "category": entry["category"],
                "confidence": entry["confidence"],
                "handler": entry["handler"],
            }

    return None


def try_handle_intent(command):
    intent = resolve_intent(command)
    if not intent:
        return {"handled": False}

    reply = intent["handler"](command)
    if reply is None:
        return {"handled": False}

    result = _reply_text(reply)
    result["intent"] = intent["intent"]
    result["category"] = intent["category"]
    result["confidence"] = intent["confidence"]
    return result
