from __future__ import annotations

from dataclasses import dataclass
from typing import Callable


@dataclass(frozen=True)
class CommandContext:
    get_period: Callable[[], str]
    tell_joke: Callable[[], str]
    wikipedia_search: Callable[[str], str]
    get_memory: Callable[[str], str | None]
    set_memory: Callable[[str, str], object]
    semantic_memory_summary: Callable[[], str]
    semantic_memory_lookup: Callable[[str], str]
    assistant_doctor_summary: Callable[..., str]
    backend_stability_summary: Callable[[], str]
    security_status_summary: Callable[[], str]
    voice_diagnostics_summary: Callable[[], str]
    current_debug_session_summary: Callable[[], str]
    debug_dashboard_summary: Callable[[], str]
    fix_approval_summary: Callable[[], str]
    fix_audit_summary: Callable[[], str]
    debug_timeline_summary: Callable[[], str]
    debug_search_summary: Callable[[str], str]
    reuse_suggestions_summary: Callable[..., str]
    debug_learning_summary: Callable[[], str]
    debug_checklist_summary: Callable[..., str]
    offline_mode_status_summary: Callable[[], str]
    offline_help_summary: Callable[[], str]
    offline_ai_status_summary: Callable[[], str]
    developer_mode_status_summary: Callable[[], str]
    focus_mode_status_summary: Callable[[], str]
    voice_trainer_status_summary: Callable[[], str]
    piper_setup_summary: Callable[[], str]
    custom_voice_setup_summary: Callable[[], str]
    custom_voice_license_status_summary: Callable[[], str]
    custom_voice_samples_summary: Callable[[], str]
    voice_status_summary: Callable[[], str]
    developer_workspace_summary: Callable[[], str]
    planner_focus_summary: Callable[[], str]
    reminder_timeline_summary: Callable[[], str]
    habit_dashboard_summary: Callable[[], str]
    goal_board_summary: Callable[[], str]
    smart_reminder_priority_summary: Callable[[], str]
    automation_history_summary: Callable[[], str]
    mobile_companion_status_summary: Callable[[], str]
    language_mode_status_summary: Callable[[], str]
    meeting_mode_summary: Callable[[], str]
    rag_library_summary: Callable[[], str]
    proactive_suggestions_summary: Callable[[], str]
    knowledge_review_queue_summary: Callable[[], str]
    learning_status_summary: Callable[[], str]
    phone_link_status_summary: Callable[[], str]
    face_security_status_summary: Callable[[], str]
    startup_auto_launch_status_summary: Callable[[], str]
    smart_home_setup_summary: Callable[[], str]
    active_window_summary: Callable[[str], str]
    local_contacts_summary: Callable[[], str]
    local_contact_lookup_summary: Callable[[str], str]
    google_contacts_summary: Callable[[], str]
    google_contact_changes_summary: Callable[[], str]
    favorite_contacts_summary: Callable[[], str]
    contact_aliases_summary: Callable[[], str]
    calendar_query_summary: Callable[[str], str | None]
    google_calendar_status_summary: Callable[[], str]
    google_calendar_today_summary: Callable[[], str]
    google_calendar_upcoming_summary: Callable[[], str]
    google_calendar_titles_summary: Callable[[], str]
    storage_report_summary: Callable[[], str]
    storage_cleanup_suggestion_summary: Callable[[], str]
    system_status_summary: Callable[[], str]
    cpu_status_summary: Callable[[], str]
    ram_status_summary: Callable[[], str]
    disk_status_summary: Callable[[], str]
    battery_status_summary: Callable[[], str]
    hardware_status_summary: Callable[[], str]
    hardware_event_history_summary: Callable[[], str]
    smart_home_status_summary: Callable[[], str]
    iot_awareness_summary: Callable[[], str]
    iot_action_history_summary: Callable[[], str]
    security_alerts_summary: Callable[[], str]
    security_logs_summary: Callable[[], str]
    voice_auth_status_summary: Callable[[], str]
    security_admin_status_summary: Callable[[], str]
    admin_permission_status_summary: Callable[[], str]
    emergency_mode_status_summary: Callable[[], str]
    emergency_quick_response_summary: Callable[[], str]
    emergency_protocol_summary: Callable[[], str]
    profile_summary: Callable[[], str]
    personal_snapshot_summary: Callable[[], str]
    preferred_language_summary: Callable[[], str]
    preferred_tone_summary: Callable[[], str]
    git_status_summary: Callable[[], str]
    git_branch_summary: Callable[[], str]
    git_remotes_summary: Callable[[], str]
    git_recent_commits_summary: Callable[[], str]
    git_repo_summary: Callable[[], str]
