const desktopBridge = typeof window !== "undefined" ? window.grandpaDesktop : undefined;

export const API_BASE = desktopBridge?.apiBase || "http://127.0.0.1:8765";
export const CHAT_API_BASE = API_BASE;

export const initialMessages = [];

export const initialChatSettings = {
  llm_provider: "ollama",
  model: "mistral:7b",
  ollama_model: "mistral:7b",
  system_prompt: "You are Grandpa Assistant, a warm, practical AI desktop assistant.",
  tone: "friendly",
  response_style: "balanced",
  tool_mode: true,
  active_model: "mistral:7b",
  llm_status: {
    provider: "ollama",
    model: "mistral:7b",
    base_url: "http://127.0.0.1:11434",
    api_key_configured: false,
    ready: false,
  },
};

export const initialChatSessions = [];

export const initialUiState = {
  overview: {
    tasks: "Loading...",
    reminders: "Loading...",
    weather: "Loading...",
    health: "Loading...",
    object_detection: "Loading...",
  },
  today: "Loading...",
  next_event: "Loading...",
  latest_note: "Loading...",
  recent_commands: [],
  notifications: [],
  dashboard: {
    tasks: [],
    reminders: [],
    events: [],
    vision: [],
    focus_summary: "",
    focus_suggestions: [],
    nextgen_highlights: [],
    reminder_timeline: {
      overdue: [],
      today: [],
      upcoming: [],
    },
  },
  settings: {
    wake_word: "Loading...",
    voice_profile: "Loading...",
    voice_popup_enabled: true,
    voice_chime_enabled: true,
    offline_mode: false,
    developer_mode: false,
    emergency_mode: false,
    focus_mode: false,
  },
  proactive: {
    focus_mode: false,
    summary: "Loading...",
    suggestions: [],
  },
  contacts: {
    favorite_contact: "Loading...",
    preview: [],
    aliases_summary: "Loading...",
    favorites_summary: "Loading...",
    recent_changes: "Loading...",
  },
  emergency: {
    location: "Loading...",
    contact: "Loading...",
    mode_enabled: false,
    protocol_summary: "Loading...",
  },
  memory: {
    preferred_language: "Loading...",
    favorite_contact: "Loading...",
    mood: {
      last_mood: "neutral",
      previous_mood: "neutral",
      previous_distinct_mood: "neutral",
      last_compound: 0,
      last_updated_at: "",
      history_count: 0,
      recent_moods: [],
      recent_history: [],
      counts: {},
      streak: 0,
    },
  },
  integrations: {
    hardware: {
      ok: false,
      device_count: 0,
      devices: [],
      recent_events: [],
      capabilities: {
        summary: "Loading...",
      },
    },
    mobile: {
      enabled: true,
      pairing: {
        active: false,
        code: "",
        requested_name: "",
        expires_in_seconds: 0,
        lan_addresses: [],
      },
      paired_devices: [],
      paired_count: 0,
      active_connections: 0,
      event_history_count: 0,
      notification_count: 0,
      lan_addresses: [],
      summary: "Loading...",
    },
    smart_home: {
      configured: false,
      enabled: false,
      device_count: 0,
      command_count: 0,
      discovered_count: 0,
      control_ready_count: 0,
      sample_commands: [],
      configured_devices: [],
      discovered_devices: [],
      recent_actions: [],
      placeholder_count: 0,
      config_example_path: "",
      setup_doc_path: "",
      supported_control_modes: [],
      summary: "Loading...",
    },
    face_security: {
      enrolled: false,
      camera_ready: false,
      embedding_ready: false,
      updated_at: "",
      summary: "Loading...",
    },
    plugins: {
      plugin_dir: "",
      total: 0,
      enabled: 0,
      disabled: 0,
      plugins: [],
    },
  },
  auth: {
    authenticated: false,
    user: null,
    preferences: {
      preferred_language: "en-US",
      response_style: "balanced",
      tone: "friendly",
      theme: "system",
      short_answers: false,
    },
    bootstrap: {
      enabled: true,
      has_users: false,
      user_count: 0,
      session_ttl_hours: 168,
      roles: ["admin", "user"],
    },
  },
  runtime: {
    running: false,
    runtime: {
      started_at: "",
      last_updated_at: "",
      autonomous_mode: true,
      thinking_mode: "adaptive",
      current_context: "casual",
      last_user_message: "",
      last_assistant_reply: "",
    },
    conversation: {
      recent_messages: [],
      last_emotion: "neutral",
      last_mood: "neutral",
    },
    goals: [],
    plugins: {
      total: 0,
      enabled: 0,
      disabled: 0,
      plugins: [],
    },
    agents: {},
    bus: {
      subscriber_count: 0,
      event_count: 0,
      history_limit: 0,
    },
  },
  object_watch: {
    active: false,
    target: "",
    summary: "Loading...",
  },
  object_detection: {
    model_name: "yolov8n.pt",
    small_object_mode: false,
    presets: [],
    alert_profile: "balanced",
    watch_alert_cooldown_seconds: 8,
  },
  object_history: [],
  object_watch_history: [],
  automation: {
    checked: 0,
    executed: [],
    failed: [],
    skipped: [],
  },
  nextgen: {
    day_plan_summary: "Loading...",
    habits_count: 0,
    goals_count: 0,
    milestones_done: 0,
    milestones_total: 0,
    meetings_count: 0,
    rag_docs_count: 0,
    automation_total: 0,
    automation_enabled: 0,
    automation_history_count: 0,
    last_automation_event: {},
    language_mode: "auto",
    voice_mode: "normal",
    mobile_enabled: false,
    mobile_device: "",
    highlights: [],
  },
};

export const initialVoiceStatus = {
  enabled: false,
  activity: "Ready",
  state_label: "ready",
  wake_word: "hey grandpa",
  voice_profile: "normal",
  follow_up_active: false,
  follow_up_remaining: 0,
  transcript: "",
  error: "",
  messages: [],
  last_reply: "",
  settings: {
    mode: "normal",
    post_wake_pause_seconds: 0.35,
    wake_listen_timeout: 5,
    wake_phrase_time_limit: 4,
    follow_up_listen_timeout: 3,
    follow_up_phrase_time_limit: 5,
    wake_match_threshold: 0.68,
    wake_requires_prefix: true,
    wake_max_prefix_words: 1,
    wake_retry_window_seconds: 6,
    follow_up_timeout_seconds: 12,
    continuous_conversation_enabled: true,
    follow_up_keep_alive_seconds: 12,
    wake_direct_fallback_enabled: true,
    interrupt_follow_up_seconds: 5,
    desktop_popup_enabled: true,
    desktop_chime_enabled: true,
  },
  diagnostics: {
    wake_detection_count: 0,
    wake_only_count: 0,
    command_count: 0,
    follow_up_command_count: 0,
    retry_window_command_count: 0,
    direct_fallback_count: 0,
    interrupt_count: 0,
    error_count: 0,
    last_heard_phrase: "",
    last_processed_command: "",
    last_wake_at: "",
    last_command_at: "",
    last_interrupt_at: "",
    last_error_at: "",
    last_error_message: "",
    wake_retry_window_active: false,
    wake_retry_remaining: 0,
  },
};

export const initialStartupState = {
  auto_launch_enabled: false,
  tray_mode: false,
  summary: "Loading...",
  portable_setup_ready: false,
  react_ui_on_tray_enabled: false,
  react_ui_on_tray_mode: "browser",
  react_frontend_ready: false,
  react_desktop_ready: false,
};
